# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: intent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "intent.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x0cintent.proto\x12\x18shardvla.protobuf.intent\"\x82\x01\n\x0bObservation\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0e\n\x06seq_id\x18\x03 \x01(\x04\x12\x14\n\x0ct_capture_ms\x18\x04 \x01(\x04\x12\x0f\n\x07payload\x18\x05 \x01(\x0c\x12\x16\n\x0epayload_format\x18\x06 \x01(\t\"\x81\x01\n\tEmbedding\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0e\n\x06seq_id\x18\x03 \x01(\x04\x12\x12\n\nt_embed_ms\x18\x04 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x12\r\n\x05shape\x18\x06 \x03(\r\x12\r\n\x05\x64type\x18\x07 \x01(\t2i\n\rIntentService\x12X\n\x06Stream\x12%.shardvla.protobuf.intent.Observation\x1a#.shardvla.protobuf.intent.Embedding(\x01\x30\x01\x62\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "intent_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_OBSERVATION"]._serialized_start = 43
    _globals["_OBSERVATION"]._serialized_end = 173
    _globals["_EMBEDDING"]._serialized_start = 176
    _globals["_EMBEDDING"]._serialized_end = 305
    _globals["_INTENTSERVICE"]._serialized_start = 307
    _globals["_INTENTSERVICE"]._serialized_end = 412
# @@protoc_insertion_point(module_scope)

